[[redirects]]
  from = "/*"
  to = "/:splat/"
  status = 301
  force = true

[[redirects]]
  from = "https://codedot-v2.netlify.app/cases/cases"
  to = "https://codedot-v2.netlify.app/cases/cases/"
  status = 301
  force = true





[[headers]]
  for = "/*"
  [headers.values]
    Last-Modified = "{{DATE}}"