[[redirects]]
  from = "/cases"
  to = "/cases/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/:splat/"
  status = 301
  force = true

[[redirects]]
  from = "/cases/cases"
  to = "/cases/cases/"
  status = 301
  force = true


[[headers]]
  for = "/*"
  [headers.values]
    Last-Modified = "{{DATE}}"